services:
  front:
    container_name: frontend
    build: ./client
    ports:
      - "3000:3000"
    expose:
      - '3000'
    depends_on:
      - back
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: ./client/src
        - action: rebuild
          path: package.json
    networks:
      - integration
    tty: true
    stdin_open: true
  back:
    container_name: backend
    build: ./server-impuls
    ports:
      - "3010:3010"
    expose:
      - '3010'
    develop:
      watch:
        - action: sync  
          path: ./server-impuls/src
          target: ./server-impuls/src
        - action: rebuild
          path: package.json
    networks:
      - integration
networks:
  integration:
    driver: bridge