services:
  front:
    container_name: frontend
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    ports:
      - "3000:3000"
    expose:
      - '3000'
    depends_on:
      - back-mongo-docs
      - back-mongo-tables
      - back-nestjs
    develop:
      watch:
        - action: sync
          path: ./client/src
          target: ./client/src
        - action: rebuild
          path: ./client/package.json
    networks:
      - integration
    tty: true
    stdin_open: true
  back-nestjs:
    container_name: backend-nestjs
    build: 
      dockerfile: Dockerfile.dev
      context: ./server-impuls        
    ports:
      - "3010:3010"
    expose:
      - '3010'
    develop:
      watch:
        - action: sync  
          path: ./server-impuls/src
          target: ./server-impuls/src
        - action: rebuild
          path: ./server-impuls/package.json
    networks:
      - integration
  back-mongo-docs:
    container_name: back-mongo-docs
    build: 
      dockerfile: Dockerfile.dev
      context: ./mongo   
    ports:
      - "3001:3001"
      - "3002:3002"
    expose:
      - '3001'
      - '3002'
    develop:
      watch:
        - action: sync  
          path: ./mongo
          target: ./mongo
    networks:
      - integration      
  back-mongo-tables:
    container_name: back-mongo-tables
    build: 
      dockerfile: Dockerfile.dev
      context: ./mongo-excel   
    ports:
      - "8081:8081"
    expose:
      - '8081'
    develop:
      watch:
        - action: sync  
          path: ./mongo-excel
          target: ./mongo-excel
    networks:
      - integration      
networks:
  integration:
    driver: bridge