services:
  nginx-react:
    container_name: ngixreactapp
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    networks:
      - integration
    depends_on:
      - back-mongo-docs
      - back-mongo-tables
      - nest-node          
  nest-node:
    container_name: nestNodeApp
    build:
      context: ./server-impuls
      dockerfile: Dockerfile.prod
    ports:
      - 3010:3010
    networks:
      - integration      
  back-mongo-docs:
    container_name: back-mongo-docs
    build: 
      dockerfile: Dockerfile.dev
      context: ./mongo   
    ports:
      - "3001:3001"
      - "3002:3002"
    expose:
      - '3001'
      - '3002'
    develop:
      watch:
        - action: sync  
          path: ./mongo
          target: ./mongo
    networks:
      - integration      
  back-mongo-tables:
    container_name: back-mongo-tables
    build: 
      dockerfile: Dockerfile.dev
      context: ./mongo-excel   
    ports:
      - "8081:8081"
    expose:
      - '8081'
    develop:
      watch:
        - action: sync  
          path: ./mongo-excel
          target: ./mongo-excel
    networks:
      - integration      
networks:
  integration:
    driver: bridge      