FROM node:lts-slim
WORKDIR /server-impuls
COPY package.json package-lock.json ./
RUN npm install
RUN apt-get update && apt-get install -y procps && rm -rf /var/lib/apt/lists/*
COPY . .
CMD ["npm", "run", "start:dev"]