# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to undo commit'
        required: true
        default: 'main'  
    
defaults:
  run: 
    working-directory: ./client
    
jobs:
  build: 
    runs-on: ubuntu-latest    

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache-dependency-path: client/package-lock.json
      - run: npm install
      - run: npm run build --if-present
  auto-revert-commit:
    needs: build
    runs-on: ubuntu-latest
    if: always() && (needs.build.result == 'failure')
    steps:
      - name: Automatic Commit Revert
        uses: 'tofu-apis/revert-commit-action@v0.0.37'
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          is-push-enabled: 'true'



      