# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to undo commit'
        required: true
        default: 'main'  
    
defaults:
  run: 
    working-directory: ./client
    
jobs:
  build: 
    runs-on: ubuntu-latest    

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache-dependency-path: client/package-lock.json
      - run: npm install
      - run: npm run build --if-present
      - name: discord-webhook
      # You may pin to the exact commit or the version.
      # uses: johnnyhuy/actions-discord-git-webhook@ba54912b26910da886c9095317d6da6182a87224
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.0
        with:
          webhook_url: https://discord.com/api/webhooks/1228005875898388501/V2mvGkRMBYSmXSHsWfBz39HHqeBYXxnhQLYKZ9UPV6Wor7ovcLeAMQe7noC0rkV76Aeg



      